### ISSUE TITLE
Tiny typo in readme

### ISSUE THREAD

**Issue by BrainCrumbz** [scottcorgan/immu#12]
Where:
Just at the beginning, section titled **What Immu Aims To Solve**: 

What:

```
includeing
->
including
```

**Comment by scottcorgan** [comment]
Want to open a PR so you get credit?

**Comment by BrainCrumbz** [comment]
Thanks for asking. We'd do that if it was something more meaningful or subtle. This is really tiny. Let's save that for a bigger contribution! :)
