### ISSUE TITLE
Provide helpers for immutable structure equality check

### ISSUE THREAD

**Issue by n1k0** [scottcorgan/immu#13]
Would be neat being able to compare two equivalent imutable structures, eg. for checking state changes:

``` js
({a: 1}) == {a: 1} // false
immu({a: 1}).eq(immu({a: 1})) // true
immu({a: 1}).eq({a: 1}) // true
```

What do you think?

**Comment by scottcorgan** [comment]
It seems like a very useful function. I know that I used Immutable's `.equals()` function a lot when I was using that library.

My only concern with adding this is violating the "naked" idea of the library. Namely, that it wouldn't add any _extra_ functionality to an object or array (except for the unavoidable `.toJS()`.

Underneath, Immu keeps the reference to the original object and that can be accessed via `.toJS()`. I think the `.eq()` method can be accomplished the same as:

``` js
import {isEqual} from 'lodash';
import immu from 'immu';

let a = immu({b: 'c'});
let b = immu({b: 'c'});

isEqual(a.toJS(), b.toJS());
```

This way, we can keep the library minimal and easily composable.

Thoughts?

**Comment by n1k0** [comment]
Yeah, there's also [deep-eql](https://www.npmjs.com/package/deep-eql) I'm using to achieve the same thing. So on one hand, I personally feel that value check vs. identity check is one of the important things immutability in js tries to fix, and so that's probably something devs might expect from such a lib.

On the other hand, I appreciate the minimalism of the lib. Maybe a proper fix would be to simply document the situation and provide an example — like you just did above — in the README?

**Comment by scottcorgan** [comment]
You make a good point about identity checking.

Perhaps there's a way to create something like `immu-eq` as a separate package to do the checking. I'm not entirely sold on creating another package, but I am VERY interested in identity checking over actual reference checking.

``` js
import immu from 'immu';
import eq from 'immu-eq';

let a = immu({b: 'c');

eq(a, a) === true;
```

**Comment by n1k0** [comment]
That would definitely work well, indeed. Personally, I keep thinking the `eq` helper could be part of the `immu` package though. It's very likely devs using it will want to compare values at some point in their project — think react users for example. Your call :)

**Comment by jimf** [comment]
Just to throw a wrinkle in this conversation, technically `toJS` can't be _fully_ relied on to be representative of the data that was made immutable. For example:

``` js
let arr = [1, 2];
let immuArr = immu(arr);
arr.unshift(0);
console.log(immuArr.toJS()[0]); // 0
console.log(immuArr[0]);        // 1
```

The argument can be made that this is a misuse of the library, but it exposes what could be a potential bug with relying on `toJS` for equality.
