### ISSUE TITLE
fork object properties

### ISSUE THREAD

**Issue by jorrit** [scottcorgan/immu#17]
In immu immutable arrays can be forked using methods like `push`, which is handy. For objects there are no such methods. Has it ever been considered to introduce methods to support operations like the following? Or would this increase the size of the library to such a degree that it is no longer tiny?

``` javascript
var oldImmu = immu({ foo: 'bar' });
var newImmu = oldImmu.set('foo', 42);
newImmu = oldImmu.rm('foo');
newImmu = oldImmu.set('hello', 'world');
newImmu = oldImmu.set('hello', [1, 2, 3]); // the array will be made immutable
newImmu = newImmu.set('hello', newImmu.hello.push(4)); // newImmu.hello.length == 4
```

**Comment by scottcorgan** [comment]
That's an interesting concept. I was trying to avoid replicating the Map/Set interface. But this would help with memory footprint.

I wonder if immu could be extensible and we could make a wrapper over immu with this interface. Thoughts?

**Comment by jorrit** [comment]
That could be done, of course, using the ToJS function, but integration would mean that it can share more code with the logic that is already in immu.

**Comment by scottcorgan** [comment]
I'm still not sold on adding more functionality to this package. I'd still LOVE to see a package that wraps immu with the set/get/rm methods you recommended.

I'm going to close for now and we can reopen if this becomes a bigger problem in the future.

**Comment by alexanderharm** [comment]
+1 for the ability to fork objects. Right now I do 
`
let tmp = old.toJS()
tmp.a.b.c = d
let new = immu(tmp)
`
which kind of defeats the purpose in my use case. For now I will go with seamless-immutable but would prefer using immu (performance is outstanding).

**Comment by scottcorgan** [comment]
@alexanderharm The idea with the immu is not to replace something like [immutable](https://github.com/facebook/immutable-js) or [mori](https://github.com/swannodette/mori) or [freezer](https://github.com/arqex/freezer). It's mainly a way to ensure you don't mutate objects without having to wrap them in an immutable data structure (like Immutable's [Map](https://facebook.github.io/immutable-js/docs/#/Map) or [List](https://facebook.github.io/immutable-js/docs/#/List)).

I am VERY open to write help methods to compose with immu like immu-set, immu-remove. BUT, the basic idea is that you would treat an immu object like a raw object, keeping it purely JS.

Does that help clarify it?
