### ISSUE TITLE
Deeply nested immu vars can be mutated using original variable

### ISSUE THREAD

**Issue by jimf** [scottcorgan/immu#19]
Example:

``` js
let data = { foo: { bar: { baz: 1 } } };
let immuData = immu(data);

data.foo.bar.baz = 2;
console.log(immuData.foo.bar.baz); // 2
```

**Comment by scottcorgan** [comment]
it's kind of a trade-off I had to make so you can compare references on properties. I don't think this is something easily solved at this time, but I'm open for PR that proves me wrong.

I'll close for now and we can reopen if this is something that becomes unbearable.
