### ISSUE TITLE
Mutating original array causes odd behavior with immu array

### ISSUE THREAD

**Issue by jimf** [scottcorgan/immu#21]
``` js
let arr = [1, 2];
let immuArr = immu(arr);
arr.unshift(0);

console.log(immuArr[0]);         // 1
console.log(immuArr[1]);         // 2
console.log(immuArr[2]);         // undefined
                                 // Looks good so far

console.log(immuArr.length);     // 3
console.log(immuArr.toString()); // '0,1,2'
console.log(immuArr.indexOf(0)); // 0
                                 // Uh oh...
```

**Comment by scottcorgan** [comment]
That's an interesting point. Although, to be fair, that seems more like a feature than a bug, don't you think?

Should the immutable version be a snapshot of the object/array at that very moment, no matter what you do to the original? I think that's the whole point of this library, at least for me. To provide an easy way to ensure that I don't use a mutable copy and I don't try to mutate the copy.

I'm going to close for now and we can continue to discuss if this is something the package should care about.

Thanks!
