### ISSUE TITLE
Arrays not completely naked

### ISSUE THREAD

**Issue by darobin** [scottcorgan/immu#22]
I ran into the following problem today:

```
 $ node -e 'var immu = require("immu"); var arr = []; console.log(Array.isArray(arr), Array.isArray(immu(arr)))'
true false
```

Basically, `Array.isArray` does not work on `immu` arrays. I haven't done very deep digging but it [looks like fixing this would require proxies](http://www.ecma-international.org/ecma-262/6.0/#sec-isarray).

At least for the time being including a warning in the docs might be the best approach?

**Comment by scottcorgan** [comment]
Ah yes! I was hoping this might not be found yet until I can figure that out. I've spent a bit on how to trick the function into thinking it's an Array, but you might be right. I don't really want to touch Proxies for this lib.

I should have an update either in the docs or the code soon.

**Comment by scottcorgan** [comment]
You are right. After much research, the only way to convince `Array.isArray` to return true for custom Array objects is to set the internal `[[Class]]` value. That's impossible in Javascript.

There is a _hacky_ way to accomplish this that may not be ideal, but could work. It's obvious but overriding the `Array.isArray` method manually to support immu arrays seems to be the only way.

``` js
var isArray = Array.isArray

Array.isArray = function (arg) {

  return typeof arg.toJS === 'function' ? isArray(arg.toJS()) : isArray(arg)
}
```

Again, not ideal, but perhaps a solution.

I'm going to let this sit for awhile while I continue to think this through.
