### ISSUE TITLE
Transparent in production

### ISSUE THREAD

**Issue by scottcorgan** [scottcorgan/immu#24]
Allow for a production build that bypasses any of the error-throwing features when in development. Basically this will just return the object or array, as is.

**Comment by rtfeldman** [comment]
Here's how we did this, back in the day: https://github.com/rtfeldman/seamless-immutable/pull/29

I dig the project, by the way! :smiley_cat:

**Comment by scottcorgan** [comment]
Appreciate the insight!

I meant to close this. Decided it was up to the user to remove from production. This was original made to put in redux middleware in an app I was working on.
