### ISSUE TITLE
how to compare tow objects is equal?

### ISSUE THREAD

**Issue by janryWang** [scottcorgan/immu#27]
```

immu({a:5}) == immu({a:5}) //It should be true

```

**Comment by scottcorgan** [comment]
In JavaScript `{a: 5} !== {a: 5}` because they are different object references. So it's not an _immu_ issue exactly.

What you can do to get around this problem is:

``` js
var obj = {a: 5}

console.log(immu(obj).toJS() === immu(obj).toJS())
```

If that's not something that you want to do, you can use [lodash's `isEqual` function](https://lodash.com/docs#isEqual)
