### ISSUE TITLE
How does immu differ from seamless-immutable?

### ISSUE THREAD

**Issue by tbo** [scottcorgan/immu#3]
How does immu differ from seamless-immutable?

https://github.com/rtfeldman/seamless-immutable

**Comment by scottcorgan** [comment]
seamless-immutable was an inspiration for this library. It is a fantastic library and I respect Richard Feldman very much!

There are a just a couple of differences:
- Less than half the size
- Throws detailed TypeError when trying to mutate a property
- Doesn't add any extra methods (compatible with native arrays/objects). seamless-immutable adds extra stuff that's not needed (https://github.com/rtfeldman/seamless-immutable#immutable-array)
