### ISSUE TITLE
Incompatible with React

### ISSUE THREAD

**Issue by ghost** [scottcorgan/immu#30]
When using something like 

``` JavaScript
const Component = () => (
  <div>
    {
       immuArray.map(() => <div>test</test>)  
    }
  </div>
)
```

React throws:

```
Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. 
```

react: 0.14.8,
immu: 2.0.1

**Comment by scottcorgan** [comment]
That is a true statement. It's been awhile since I've done any React.

I'm VERY open to PRs to fix this.

In the meantime, you can just add `.toJS()` to the end of that.

**Comment by MoeSattler** [comment]
I'll did a little bit into the immu code. Any idea what could cause the issue so I have a starting point? :)

**Comment by ghost** [comment]
@scottcorgan I looked into the code. the issue is that immu doesn't handle Symbols. [This](https://github.com/scottcorgan/immu/blob/master/src/index.js#L115-L124) turns it into an object. You might run into similar issues with Date.

<img width="251" alt="screen shot 2016-10-13 at 20 44 11" src="https://cloud.githubusercontent.com/assets/8615251/19362164/d995648c-9185-11e6-8490-28b50960b89e.png">

So this is not a React specific problem.
