### ISSUE TITLE
Performance of Object.seal and Object.freeze

### ISSUE THREAD

**Issue by trueadm** [scottcorgan/immu#4]
I noticed that you posted a link to the JSperf comparison of Object.freeze and Object.seal. In recent Chrome updates, Object.freeze/Object.seal can be _faster_ in certain cases. Do you plan on supporting Object.freeze/Object.seal for these cases?

**Comment by scottcorgan** [comment]
Right now, it uses Object.freeze in development in order to throw an error when you try to add/remove a property from and element or array.

The ultimate goal is to provide defenses in development and speed in production.
