### ISSUE TITLE
Stop avoiding Object.freeze

### ISSUE THREAD

**Issue by erights** [scottcorgan/immu#5]
I followed your link to http://jsperf.com/freeze-vs-seal-vs-normal/3
I ran these tests on Chrome Canary, FF Nightly, and Webkit Nightly (Safari). In all cases, there was no speed penalty for Object.freeze and Object.seal.

Please make this wonderfully simple library even simpler by using Object.freeze as it was meant to be used. Thanks.

**Comment by scottcorgan** [comment]
My assumption was that this was a more drastic difference on mobile. But, apparently it's not. It will be frozen by default moving forward.
