### ISSUE TITLE
List other immutable data libraries

### ISSUE THREAD

**Issue by scottcorgan** [scottcorgan/immu#7]
- [immutable](https://github.com/facebook/immutable-js)
- [seamless-immutable](https://github.com/rtfeldman/seamless-immutable)
- [freezer](https://github.com/arqex/freezer)
- [mori](https://github.com/swannodette/mori)
- [deep-freeze](https://www.npmjs.com/package/deep-freeze)

**Comment by gcanti** [comment]
Hi @scottcorgan,
Another tiny, naked, immutable data structure library: [tcomb](https://github.com/gcanti/tcomb)

**Comment by scottcorgan** [comment]
Nice one! Thanks!

**Comment by gcanti** [comment]
Thanks, if you don't mind I'll add your library to a section "Similar projects" in my README.md

**Comment by scottcorgan** [comment]
Sounds good

**Comment by tinkertrain** [comment]
One more: https://github.com/winkler1/icedam

**Comment by scottcorgan** [comment]
Sweet!

**Comment by scottcorgan** [comment]
https://github.com/Yomguithereal/baobab

**Comment by gcanti** [comment]
https://github.com/christianalfoni/immutable-store

**Comment by scottcorgan** [comment]
@gcanti another good one! Thanks!

**Comment by scottcorgan** [comment]
All libraries are listed in the README now
